# Generated by Django 4.0.1 on 2022-01-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(blank=True, default=list, help_text='All the chats for the movie session')),
                ('date', models.DateTimeField(auto_now=True)),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='movie.moviesessionmodel')),
            ],
        ),
    ]
