# Generated by Django 4.0.1 on 2022-01-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is the field for the name of the movie', max_length=1200)),
                ('source', models.URLField(help_text='This is the field for the location of the movie. Must be a URL')),
                ('coverPicture', models.ImageField(help_text='This is the field for the cover image of the movie.', upload_to='cover/')),
            ],
        ),
    ]
