# Generated by Django 3.2.4 on 2021-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='coverPicture',
            field=models.ImageField(help_text='This is the field for the cover image of the movie.', upload_to='cover/'),
        ),
    ]
