# Generated by Django 4.0.1 on 2022-01-18 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sessionStatus', models.JSONField(blank=True, default=dict, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_session', to='core.moviemodel')),
            ],
        ),
    ]
