# Generated by Django 3.2.4 on 2021-06-09 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_moviemodel_coverpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_session', to='core.moviemodel')),
            ],
        ),
    ]
