# Generated by Django 3.2.4 on 2021-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesessionmodel',
            name='sessionStatus',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
